baseURL = "https://tomkimpson.github.io/"
languageCode = "en-us"
title = "Tom Kimpson"

theme = "hyde"


[Menus]
  main = [
      {Name = "Research", URL = "/publications/", weight=1}, 
      {Name = "Code", URL = "/code/",weight=2},
      {Name = "News", URL = "/news/",weight=3}
  ]

[params]
  themeColor = "theme-base-0y"
  description = "Research Fellow in Astrophysics @ UniMelb/OzGrav"
  GitUsername = "tomkimpson"
  authorImage = "/images/avatar_old.jpg"

[markup.goldmark.renderer]
  unsafe= true

